/* automatically generated by rust-bindgen 0.59.2 */

pub const YAML_NULL_TAG: &[u8; 23usize] = b"tag:yaml.org,2002:null\0";
pub const YAML_BOOL_TAG: &[u8; 23usize] = b"tag:yaml.org,2002:bool\0";
pub const YAML_STR_TAG: &[u8; 22usize] = b"tag:yaml.org,2002:str\0";
pub const YAML_INT_TAG: &[u8; 22usize] = b"tag:yaml.org,2002:int\0";
pub const YAML_FLOAT_TAG: &[u8; 24usize] = b"tag:yaml.org,2002:float\0";
pub const YAML_TIMESTAMP_TAG: &[u8; 28usize] = b"tag:yaml.org,2002:timestamp\0";
pub const YAML_SEQ_TAG: &[u8; 22usize] = b"tag:yaml.org,2002:seq\0";
pub const YAML_MAP_TAG: &[u8; 22usize] = b"tag:yaml.org,2002:map\0";
pub const YAML_DEFAULT_SCALAR_TAG: &[u8; 22usize] = b"tag:yaml.org,2002:str\0";
pub const YAML_DEFAULT_SEQUENCE_TAG: &[u8; 22usize] =
	b"tag:yaml.org,2002:seq\0";
pub const YAML_DEFAULT_MAPPING_TAG: &[u8; 22usize] = b"tag:yaml.org,2002:map\0";
pub type size_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
	_unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
	_unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
	_unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
	pub _flags: ::std::os::raw::c_int,
	pub _IO_read_ptr: *mut ::std::os::raw::c_char,
	pub _IO_read_end: *mut ::std::os::raw::c_char,
	pub _IO_read_base: *mut ::std::os::raw::c_char,
	pub _IO_write_base: *mut ::std::os::raw::c_char,
	pub _IO_write_ptr: *mut ::std::os::raw::c_char,
	pub _IO_write_end: *mut ::std::os::raw::c_char,
	pub _IO_buf_base: *mut ::std::os::raw::c_char,
	pub _IO_buf_end: *mut ::std::os::raw::c_char,
	pub _IO_save_base: *mut ::std::os::raw::c_char,
	pub _IO_backup_base: *mut ::std::os::raw::c_char,
	pub _IO_save_end: *mut ::std::os::raw::c_char,
	pub _markers: *mut _IO_marker,
	pub _chain: *mut _IO_FILE,
	pub _fileno: ::std::os::raw::c_int,
	pub _flags2: ::std::os::raw::c_int,
	pub _old_offset: __off_t,
	pub _cur_column: ::std::os::raw::c_ushort,
	pub _vtable_offset: ::std::os::raw::c_schar,
	pub _shortbuf: [::std::os::raw::c_char; 1usize],
	pub _lock: *mut _IO_lock_t,
	pub _offset: __off64_t,
	pub _codecvt: *mut _IO_codecvt,
	pub _wide_data: *mut _IO_wide_data,
	pub _freeres_list: *mut _IO_FILE,
	pub _freeres_buf: *mut ::std::os::raw::c_void,
	pub __pad5: size_t,
	pub _mode: ::std::os::raw::c_int,
	pub _unused2: [::std::os::raw::c_char; 20usize],
}
pub type yaml_char_t = ::std::os::raw::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_version_directive_s {
	pub major: ::std::os::raw::c_int,
	pub minor: ::std::os::raw::c_int,
}
pub type yaml_version_directive_t = yaml_version_directive_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_tag_directive_s {
	pub handle: *mut yaml_char_t,
	pub prefix: *mut yaml_char_t,
}
pub type yaml_tag_directive_t = yaml_tag_directive_s;
pub const yaml_encoding_e_YAML_ANY_ENCODING: yaml_encoding_e = 0;
pub const yaml_encoding_e_YAML_UTF8_ENCODING: yaml_encoding_e = 1;
pub const yaml_encoding_e_YAML_UTF16LE_ENCODING: yaml_encoding_e = 2;
pub const yaml_encoding_e_YAML_UTF16BE_ENCODING: yaml_encoding_e = 3;
pub type yaml_encoding_e = ::std::os::raw::c_uint;
pub use self::yaml_encoding_e as yaml_encoding_t;
pub const yaml_break_e_YAML_ANY_BREAK: yaml_break_e = 0;
pub const yaml_break_e_YAML_CR_BREAK: yaml_break_e = 1;
pub const yaml_break_e_YAML_LN_BREAK: yaml_break_e = 2;
pub const yaml_break_e_YAML_CRLN_BREAK: yaml_break_e = 3;
pub type yaml_break_e = ::std::os::raw::c_uint;
pub use self::yaml_break_e as yaml_break_t;
pub const yaml_error_type_e_YAML_NO_ERROR: yaml_error_type_e = 0;
pub const yaml_error_type_e_YAML_MEMORY_ERROR: yaml_error_type_e = 1;
pub const yaml_error_type_e_YAML_READER_ERROR: yaml_error_type_e = 2;
pub const yaml_error_type_e_YAML_SCANNER_ERROR: yaml_error_type_e = 3;
pub const yaml_error_type_e_YAML_PARSER_ERROR: yaml_error_type_e = 4;
pub const yaml_error_type_e_YAML_COMPOSER_ERROR: yaml_error_type_e = 5;
pub const yaml_error_type_e_YAML_WRITER_ERROR: yaml_error_type_e = 6;
pub const yaml_error_type_e_YAML_EMITTER_ERROR: yaml_error_type_e = 7;
pub type yaml_error_type_e = ::std::os::raw::c_uint;
pub use self::yaml_error_type_e as yaml_error_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_mark_s {
	pub index: size_t,
	pub line: size_t,
	pub column: size_t,
}
pub type yaml_mark_t = yaml_mark_s;
pub const yaml_scalar_style_e_YAML_ANY_SCALAR_STYLE: yaml_scalar_style_e = 0;
pub const yaml_scalar_style_e_YAML_PLAIN_SCALAR_STYLE: yaml_scalar_style_e = 1;
pub const yaml_scalar_style_e_YAML_SINGLE_QUOTED_SCALAR_STYLE:
	yaml_scalar_style_e = 2;
pub const yaml_scalar_style_e_YAML_DOUBLE_QUOTED_SCALAR_STYLE:
	yaml_scalar_style_e = 3;
pub const yaml_scalar_style_e_YAML_LITERAL_SCALAR_STYLE: yaml_scalar_style_e =
	4;
pub const yaml_scalar_style_e_YAML_FOLDED_SCALAR_STYLE: yaml_scalar_style_e = 5;
pub type yaml_scalar_style_e = ::std::os::raw::c_uint;
pub use self::yaml_scalar_style_e as yaml_scalar_style_t;
pub const yaml_sequence_style_e_YAML_ANY_SEQUENCE_STYLE: yaml_sequence_style_e =
	0;
pub const yaml_sequence_style_e_YAML_BLOCK_SEQUENCE_STYLE:
	yaml_sequence_style_e = 1;
pub const yaml_sequence_style_e_YAML_FLOW_SEQUENCE_STYLE:
	yaml_sequence_style_e = 2;
pub type yaml_sequence_style_e = ::std::os::raw::c_uint;
pub use self::yaml_sequence_style_e as yaml_sequence_style_t;
pub const yaml_mapping_style_e_YAML_ANY_MAPPING_STYLE: yaml_mapping_style_e = 0;
pub const yaml_mapping_style_e_YAML_BLOCK_MAPPING_STYLE: yaml_mapping_style_e =
	1;
pub const yaml_mapping_style_e_YAML_FLOW_MAPPING_STYLE: yaml_mapping_style_e =
	2;
pub type yaml_mapping_style_e = ::std::os::raw::c_uint;
pub use self::yaml_mapping_style_e as yaml_mapping_style_t;
pub const yaml_token_type_e_YAML_NO_TOKEN: yaml_token_type_e = 0;
pub const yaml_token_type_e_YAML_STREAM_START_TOKEN: yaml_token_type_e = 1;
pub const yaml_token_type_e_YAML_STREAM_END_TOKEN: yaml_token_type_e = 2;
pub const yaml_token_type_e_YAML_VERSION_DIRECTIVE_TOKEN: yaml_token_type_e = 3;
pub const yaml_token_type_e_YAML_TAG_DIRECTIVE_TOKEN: yaml_token_type_e = 4;
pub const yaml_token_type_e_YAML_DOCUMENT_START_TOKEN: yaml_token_type_e = 5;
pub const yaml_token_type_e_YAML_DOCUMENT_END_TOKEN: yaml_token_type_e = 6;
pub const yaml_token_type_e_YAML_BLOCK_SEQUENCE_START_TOKEN: yaml_token_type_e =
	7;
pub const yaml_token_type_e_YAML_BLOCK_MAPPING_START_TOKEN: yaml_token_type_e =
	8;
pub const yaml_token_type_e_YAML_BLOCK_END_TOKEN: yaml_token_type_e = 9;
pub const yaml_token_type_e_YAML_FLOW_SEQUENCE_START_TOKEN: yaml_token_type_e =
	10;
pub const yaml_token_type_e_YAML_FLOW_SEQUENCE_END_TOKEN: yaml_token_type_e =
	11;
pub const yaml_token_type_e_YAML_FLOW_MAPPING_START_TOKEN: yaml_token_type_e =
	12;
pub const yaml_token_type_e_YAML_FLOW_MAPPING_END_TOKEN: yaml_token_type_e = 13;
pub const yaml_token_type_e_YAML_BLOCK_ENTRY_TOKEN: yaml_token_type_e = 14;
pub const yaml_token_type_e_YAML_FLOW_ENTRY_TOKEN: yaml_token_type_e = 15;
pub const yaml_token_type_e_YAML_KEY_TOKEN: yaml_token_type_e = 16;
pub const yaml_token_type_e_YAML_VALUE_TOKEN: yaml_token_type_e = 17;
pub const yaml_token_type_e_YAML_ALIAS_TOKEN: yaml_token_type_e = 18;
pub const yaml_token_type_e_YAML_ANCHOR_TOKEN: yaml_token_type_e = 19;
pub const yaml_token_type_e_YAML_TAG_TOKEN: yaml_token_type_e = 20;
pub const yaml_token_type_e_YAML_SCALAR_TOKEN: yaml_token_type_e = 21;
pub type yaml_token_type_e = ::std::os::raw::c_uint;
pub use self::yaml_token_type_e as yaml_token_type_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct yaml_token_s {
	pub type_: yaml_token_type_t,
	pub data: yaml_token_s__bindgen_ty_1,
	pub start_mark: yaml_mark_t,
	pub end_mark: yaml_mark_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union yaml_token_s__bindgen_ty_1 {
	pub stream_start: yaml_token_s__bindgen_ty_1__bindgen_ty_1,
	pub alias: yaml_token_s__bindgen_ty_1__bindgen_ty_2,
	pub anchor: yaml_token_s__bindgen_ty_1__bindgen_ty_3,
	pub tag: yaml_token_s__bindgen_ty_1__bindgen_ty_4,
	pub scalar: yaml_token_s__bindgen_ty_1__bindgen_ty_5,
	pub version_directive: yaml_token_s__bindgen_ty_1__bindgen_ty_6,
	pub tag_directive: yaml_token_s__bindgen_ty_1__bindgen_ty_7,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_1 {
	pub encoding: yaml_encoding_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_2 {
	pub value: *mut yaml_char_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_3 {
	pub value: *mut yaml_char_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_4 {
	pub handle: *mut yaml_char_t,
	pub suffix: *mut yaml_char_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_5 {
	pub value: *mut yaml_char_t,
	pub length: size_t,
	pub style: yaml_scalar_style_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_6 {
	pub major: ::std::os::raw::c_int,
	pub minor: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_token_s__bindgen_ty_1__bindgen_ty_7 {
	pub handle: *mut yaml_char_t,
	pub prefix: *mut yaml_char_t,
}
pub type yaml_token_t = yaml_token_s;
pub const yaml_event_type_e_YAML_NO_EVENT: yaml_event_type_e = 0;
pub const yaml_event_type_e_YAML_STREAM_START_EVENT: yaml_event_type_e = 1;
pub const yaml_event_type_e_YAML_STREAM_END_EVENT: yaml_event_type_e = 2;
pub const yaml_event_type_e_YAML_DOCUMENT_START_EVENT: yaml_event_type_e = 3;
pub const yaml_event_type_e_YAML_DOCUMENT_END_EVENT: yaml_event_type_e = 4;
pub const yaml_event_type_e_YAML_ALIAS_EVENT: yaml_event_type_e = 5;
pub const yaml_event_type_e_YAML_SCALAR_EVENT: yaml_event_type_e = 6;
pub const yaml_event_type_e_YAML_SEQUENCE_START_EVENT: yaml_event_type_e = 7;
pub const yaml_event_type_e_YAML_SEQUENCE_END_EVENT: yaml_event_type_e = 8;
pub const yaml_event_type_e_YAML_MAPPING_START_EVENT: yaml_event_type_e = 9;
pub const yaml_event_type_e_YAML_MAPPING_END_EVENT: yaml_event_type_e = 10;
pub type yaml_event_type_e = ::std::os::raw::c_uint;
pub use self::yaml_event_type_e as yaml_event_type_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct yaml_event_s {
	pub type_: yaml_event_type_t,
	pub data: yaml_event_s__bindgen_ty_1,
	pub start_mark: yaml_mark_t,
	pub end_mark: yaml_mark_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union yaml_event_s__bindgen_ty_1 {
	pub stream_start: yaml_event_s__bindgen_ty_1__bindgen_ty_1,
	pub document_start: yaml_event_s__bindgen_ty_1__bindgen_ty_2,
	pub document_end: yaml_event_s__bindgen_ty_1__bindgen_ty_3,
	pub alias: yaml_event_s__bindgen_ty_1__bindgen_ty_4,
	pub scalar: yaml_event_s__bindgen_ty_1__bindgen_ty_5,
	pub sequence_start: yaml_event_s__bindgen_ty_1__bindgen_ty_6,
	pub mapping_start: yaml_event_s__bindgen_ty_1__bindgen_ty_7,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_1 {
	pub encoding: yaml_encoding_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_2 {
	pub version_directive: *mut yaml_version_directive_t,
	pub tag_directives: yaml_event_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1,
	pub implicit: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1 {
	pub start: *mut yaml_tag_directive_t,
	pub end: *mut yaml_tag_directive_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_3 {
	pub implicit: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_4 {
	pub anchor: *mut yaml_char_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_5 {
	pub anchor: *mut yaml_char_t,
	pub tag: *mut yaml_char_t,
	pub value: *mut yaml_char_t,
	pub length: size_t,
	pub plain_implicit: ::std::os::raw::c_int,
	pub quoted_implicit: ::std::os::raw::c_int,
	pub style: yaml_scalar_style_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_6 {
	pub anchor: *mut yaml_char_t,
	pub tag: *mut yaml_char_t,
	pub implicit: ::std::os::raw::c_int,
	pub style: yaml_sequence_style_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_event_s__bindgen_ty_1__bindgen_ty_7 {
	pub anchor: *mut yaml_char_t,
	pub tag: *mut yaml_char_t,
	pub implicit: ::std::os::raw::c_int,
	pub style: yaml_mapping_style_t,
}
pub type yaml_event_t = yaml_event_s;
pub const yaml_node_type_e_YAML_NO_NODE: yaml_node_type_e = 0;
pub const yaml_node_type_e_YAML_SCALAR_NODE: yaml_node_type_e = 1;
pub const yaml_node_type_e_YAML_SEQUENCE_NODE: yaml_node_type_e = 2;
pub const yaml_node_type_e_YAML_MAPPING_NODE: yaml_node_type_e = 3;
pub type yaml_node_type_e = ::std::os::raw::c_uint;
pub use self::yaml_node_type_e as yaml_node_type_t;
pub type yaml_node_t = yaml_node_s;
pub type yaml_node_item_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_node_pair_s {
	pub key: ::std::os::raw::c_int,
	pub value: ::std::os::raw::c_int,
}
pub type yaml_node_pair_t = yaml_node_pair_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct yaml_node_s {
	pub type_: yaml_node_type_t,
	pub tag: *mut yaml_char_t,
	pub data: yaml_node_s__bindgen_ty_1,
	pub start_mark: yaml_mark_t,
	pub end_mark: yaml_mark_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union yaml_node_s__bindgen_ty_1 {
	pub scalar: yaml_node_s__bindgen_ty_1__bindgen_ty_1,
	pub sequence: yaml_node_s__bindgen_ty_1__bindgen_ty_2,
	pub mapping: yaml_node_s__bindgen_ty_1__bindgen_ty_3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_node_s__bindgen_ty_1__bindgen_ty_1 {
	pub value: *mut yaml_char_t,
	pub length: size_t,
	pub style: yaml_scalar_style_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_node_s__bindgen_ty_1__bindgen_ty_2 {
	pub items: yaml_node_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1,
	pub style: yaml_sequence_style_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_node_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1 {
	pub start: *mut yaml_node_item_t,
	pub end: *mut yaml_node_item_t,
	pub top: *mut yaml_node_item_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_node_s__bindgen_ty_1__bindgen_ty_3 {
	pub pairs: yaml_node_s__bindgen_ty_1__bindgen_ty_3__bindgen_ty_1,
	pub style: yaml_mapping_style_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_node_s__bindgen_ty_1__bindgen_ty_3__bindgen_ty_1 {
	pub start: *mut yaml_node_pair_t,
	pub end: *mut yaml_node_pair_t,
	pub top: *mut yaml_node_pair_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_document_s {
	pub nodes: yaml_document_s__bindgen_ty_1,
	pub version_directive: *mut yaml_version_directive_t,
	pub tag_directives: yaml_document_s__bindgen_ty_2,
	pub start_implicit: ::std::os::raw::c_int,
	pub end_implicit: ::std::os::raw::c_int,
	pub start_mark: yaml_mark_t,
	pub end_mark: yaml_mark_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_document_s__bindgen_ty_1 {
	pub start: *mut yaml_node_t,
	pub end: *mut yaml_node_t,
	pub top: *mut yaml_node_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_document_s__bindgen_ty_2 {
	pub start: *mut yaml_tag_directive_t,
	pub end: *mut yaml_tag_directive_t,
}
pub type yaml_document_t = yaml_document_s;
pub type yaml_read_handler_t = ::std::option::Option<
	unsafe extern "C" fn(
		data: *mut ::std::os::raw::c_void,
		buffer: *mut ::std::os::raw::c_uchar,
		size: size_t,
		size_read: *mut size_t,
	) -> ::std::os::raw::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_simple_key_s {
	pub possible: ::std::os::raw::c_int,
	pub required: ::std::os::raw::c_int,
	pub token_number: size_t,
	pub mark: yaml_mark_t,
}
pub type yaml_simple_key_t = yaml_simple_key_s;
pub const yaml_parser_state_e_YAML_PARSE_STREAM_START_STATE:
	yaml_parser_state_e = 0;
pub const yaml_parser_state_e_YAML_PARSE_IMPLICIT_DOCUMENT_START_STATE:
	yaml_parser_state_e = 1;
pub const yaml_parser_state_e_YAML_PARSE_DOCUMENT_START_STATE:
	yaml_parser_state_e = 2;
pub const yaml_parser_state_e_YAML_PARSE_DOCUMENT_CONTENT_STATE:
	yaml_parser_state_e = 3;
pub const yaml_parser_state_e_YAML_PARSE_DOCUMENT_END_STATE:
	yaml_parser_state_e = 4;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_NODE_STATE: yaml_parser_state_e =
	5;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_NODE_OR_INDENTLESS_SEQUENCE_STATE : yaml_parser_state_e = 6 ;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_NODE_STATE: yaml_parser_state_e =
	7;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_SEQUENCE_FIRST_ENTRY_STATE:
	yaml_parser_state_e = 8;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_SEQUENCE_ENTRY_STATE:
	yaml_parser_state_e = 9;
pub const yaml_parser_state_e_YAML_PARSE_INDENTLESS_SEQUENCE_ENTRY_STATE:
	yaml_parser_state_e = 10;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_MAPPING_FIRST_KEY_STATE:
	yaml_parser_state_e = 11;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_MAPPING_KEY_STATE:
	yaml_parser_state_e = 12;
pub const yaml_parser_state_e_YAML_PARSE_BLOCK_MAPPING_VALUE_STATE:
	yaml_parser_state_e = 13;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_SEQUENCE_FIRST_ENTRY_STATE:
	yaml_parser_state_e = 14;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_SEQUENCE_ENTRY_STATE:
	yaml_parser_state_e = 15;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_SEQUENCE_ENTRY_MAPPING_KEY_STATE : yaml_parser_state_e = 16 ;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_SEQUENCE_ENTRY_MAPPING_VALUE_STATE : yaml_parser_state_e = 17 ;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_SEQUENCE_ENTRY_MAPPING_END_STATE : yaml_parser_state_e = 18 ;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_MAPPING_FIRST_KEY_STATE:
	yaml_parser_state_e = 19;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_MAPPING_KEY_STATE:
	yaml_parser_state_e = 20;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_MAPPING_VALUE_STATE:
	yaml_parser_state_e = 21;
pub const yaml_parser_state_e_YAML_PARSE_FLOW_MAPPING_EMPTY_VALUE_STATE:
	yaml_parser_state_e = 22;
pub const yaml_parser_state_e_YAML_PARSE_END_STATE: yaml_parser_state_e = 23;
pub type yaml_parser_state_e = ::std::os::raw::c_uint;
pub use self::yaml_parser_state_e as yaml_parser_state_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_alias_data_s {
	pub anchor: *mut yaml_char_t,
	pub index: ::std::os::raw::c_int,
	pub mark: yaml_mark_t,
}
pub type yaml_alias_data_t = yaml_alias_data_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct yaml_parser_s {
	pub error: yaml_error_type_t,
	pub problem: *const ::std::os::raw::c_char,
	pub problem_offset: size_t,
	pub problem_value: ::std::os::raw::c_int,
	pub problem_mark: yaml_mark_t,
	pub context: *const ::std::os::raw::c_char,
	pub context_mark: yaml_mark_t,
	pub read_handler: yaml_read_handler_t,
	pub read_handler_data: *mut ::std::os::raw::c_void,
	pub input: yaml_parser_s__bindgen_ty_1,
	pub eof: ::std::os::raw::c_int,
	pub buffer: yaml_parser_s__bindgen_ty_2,
	pub unread: size_t,
	pub raw_buffer: yaml_parser_s__bindgen_ty_3,
	pub encoding: yaml_encoding_t,
	pub offset: size_t,
	pub mark: yaml_mark_t,
	pub stream_start_produced: ::std::os::raw::c_int,
	pub stream_end_produced: ::std::os::raw::c_int,
	pub flow_level: ::std::os::raw::c_int,
	pub tokens: yaml_parser_s__bindgen_ty_4,
	pub tokens_parsed: size_t,
	pub token_available: ::std::os::raw::c_int,
	pub indents: yaml_parser_s__bindgen_ty_5,
	pub indent: ::std::os::raw::c_int,
	pub simple_key_allowed: ::std::os::raw::c_int,
	pub simple_keys: yaml_parser_s__bindgen_ty_6,
	pub states: yaml_parser_s__bindgen_ty_7,
	pub state: yaml_parser_state_t,
	pub marks: yaml_parser_s__bindgen_ty_8,
	pub tag_directives: yaml_parser_s__bindgen_ty_9,
	pub aliases: yaml_parser_s__bindgen_ty_10,
	pub document: *mut yaml_document_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union yaml_parser_s__bindgen_ty_1 {
	pub string: yaml_parser_s__bindgen_ty_1__bindgen_ty_1,
	pub file: *mut FILE,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_1__bindgen_ty_1 {
	pub start: *const ::std::os::raw::c_uchar,
	pub end: *const ::std::os::raw::c_uchar,
	pub current: *const ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_2 {
	pub start: *mut yaml_char_t,
	pub end: *mut yaml_char_t,
	pub pointer: *mut yaml_char_t,
	pub last: *mut yaml_char_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_3 {
	pub start: *mut ::std::os::raw::c_uchar,
	pub end: *mut ::std::os::raw::c_uchar,
	pub pointer: *mut ::std::os::raw::c_uchar,
	pub last: *mut ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_4 {
	pub start: *mut yaml_token_t,
	pub end: *mut yaml_token_t,
	pub head: *mut yaml_token_t,
	pub tail: *mut yaml_token_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_5 {
	pub start: *mut ::std::os::raw::c_int,
	pub end: *mut ::std::os::raw::c_int,
	pub top: *mut ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_6 {
	pub start: *mut yaml_simple_key_t,
	pub end: *mut yaml_simple_key_t,
	pub top: *mut yaml_simple_key_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_7 {
	pub start: *mut yaml_parser_state_t,
	pub end: *mut yaml_parser_state_t,
	pub top: *mut yaml_parser_state_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_8 {
	pub start: *mut yaml_mark_t,
	pub end: *mut yaml_mark_t,
	pub top: *mut yaml_mark_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_9 {
	pub start: *mut yaml_tag_directive_t,
	pub end: *mut yaml_tag_directive_t,
	pub top: *mut yaml_tag_directive_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_parser_s__bindgen_ty_10 {
	pub start: *mut yaml_alias_data_t,
	pub end: *mut yaml_alias_data_t,
	pub top: *mut yaml_alias_data_t,
}
pub type yaml_parser_t = yaml_parser_s;
pub type yaml_write_handler_t = ::std::option::Option<
	unsafe extern "C" fn(
		data: *mut ::std::os::raw::c_void,
		buffer: *mut ::std::os::raw::c_uchar,
		size: size_t,
	) -> ::std::os::raw::c_int,
>;
pub const yaml_emitter_state_e_YAML_EMIT_STREAM_START_STATE:
	yaml_emitter_state_e = 0;
pub const yaml_emitter_state_e_YAML_EMIT_FIRST_DOCUMENT_START_STATE:
	yaml_emitter_state_e = 1;
pub const yaml_emitter_state_e_YAML_EMIT_DOCUMENT_START_STATE:
	yaml_emitter_state_e = 2;
pub const yaml_emitter_state_e_YAML_EMIT_DOCUMENT_CONTENT_STATE:
	yaml_emitter_state_e = 3;
pub const yaml_emitter_state_e_YAML_EMIT_DOCUMENT_END_STATE:
	yaml_emitter_state_e = 4;
pub const yaml_emitter_state_e_YAML_EMIT_FLOW_SEQUENCE_FIRST_ITEM_STATE:
	yaml_emitter_state_e = 5;
pub const yaml_emitter_state_e_YAML_EMIT_FLOW_SEQUENCE_ITEM_STATE:
	yaml_emitter_state_e = 6;
pub const yaml_emitter_state_e_YAML_EMIT_FLOW_MAPPING_FIRST_KEY_STATE:
	yaml_emitter_state_e = 7;
pub const yaml_emitter_state_e_YAML_EMIT_FLOW_MAPPING_KEY_STATE:
	yaml_emitter_state_e = 8;
pub const yaml_emitter_state_e_YAML_EMIT_FLOW_MAPPING_SIMPLE_VALUE_STATE:
	yaml_emitter_state_e = 9;
pub const yaml_emitter_state_e_YAML_EMIT_FLOW_MAPPING_VALUE_STATE:
	yaml_emitter_state_e = 10;
pub const yaml_emitter_state_e_YAML_EMIT_BLOCK_SEQUENCE_FIRST_ITEM_STATE:
	yaml_emitter_state_e = 11;
pub const yaml_emitter_state_e_YAML_EMIT_BLOCK_SEQUENCE_ITEM_STATE:
	yaml_emitter_state_e = 12;
pub const yaml_emitter_state_e_YAML_EMIT_BLOCK_MAPPING_FIRST_KEY_STATE:
	yaml_emitter_state_e = 13;
pub const yaml_emitter_state_e_YAML_EMIT_BLOCK_MAPPING_KEY_STATE:
	yaml_emitter_state_e = 14;
pub const yaml_emitter_state_e_YAML_EMIT_BLOCK_MAPPING_SIMPLE_VALUE_STATE:
	yaml_emitter_state_e = 15;
pub const yaml_emitter_state_e_YAML_EMIT_BLOCK_MAPPING_VALUE_STATE:
	yaml_emitter_state_e = 16;
pub const yaml_emitter_state_e_YAML_EMIT_END_STATE: yaml_emitter_state_e = 17;
pub type yaml_emitter_state_e = ::std::os::raw::c_uint;
pub use self::yaml_emitter_state_e as yaml_emitter_state_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_anchors_s {
	pub references: ::std::os::raw::c_int,
	pub anchor: ::std::os::raw::c_int,
	pub serialized: ::std::os::raw::c_int,
}
pub type yaml_anchors_t = yaml_anchors_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct yaml_emitter_s {
	pub error: yaml_error_type_t,
	pub problem: *const ::std::os::raw::c_char,
	pub write_handler: yaml_write_handler_t,
	pub write_handler_data: *mut ::std::os::raw::c_void,
	pub output: yaml_emitter_s__bindgen_ty_1,
	pub buffer: yaml_emitter_s__bindgen_ty_2,
	pub raw_buffer: yaml_emitter_s__bindgen_ty_3,
	pub encoding: yaml_encoding_t,
	pub canonical: ::std::os::raw::c_int,
	pub best_indent: ::std::os::raw::c_int,
	pub best_width: ::std::os::raw::c_int,
	pub unicode: ::std::os::raw::c_int,
	pub line_break: yaml_break_t,
	pub states: yaml_emitter_s__bindgen_ty_4,
	pub state: yaml_emitter_state_t,
	pub events: yaml_emitter_s__bindgen_ty_5,
	pub indents: yaml_emitter_s__bindgen_ty_6,
	pub tag_directives: yaml_emitter_s__bindgen_ty_7,
	pub indent: ::std::os::raw::c_int,
	pub flow_level: ::std::os::raw::c_int,
	pub root_context: ::std::os::raw::c_int,
	pub sequence_context: ::std::os::raw::c_int,
	pub mapping_context: ::std::os::raw::c_int,
	pub simple_key_context: ::std::os::raw::c_int,
	pub line: ::std::os::raw::c_int,
	pub column: ::std::os::raw::c_int,
	pub whitespace: ::std::os::raw::c_int,
	pub indention: ::std::os::raw::c_int,
	pub open_ended: ::std::os::raw::c_int,
	pub anchor_data: yaml_emitter_s__bindgen_ty_8,
	pub tag_data: yaml_emitter_s__bindgen_ty_9,
	pub scalar_data: yaml_emitter_s__bindgen_ty_10,
	pub opened: ::std::os::raw::c_int,
	pub closed: ::std::os::raw::c_int,
	pub anchors: *mut yaml_anchors_t,
	pub last_anchor_id: ::std::os::raw::c_int,
	pub document: *mut yaml_document_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union yaml_emitter_s__bindgen_ty_1 {
	pub string: yaml_emitter_s__bindgen_ty_1__bindgen_ty_1,
	pub file: *mut FILE,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_1__bindgen_ty_1 {
	pub buffer: *mut ::std::os::raw::c_uchar,
	pub size: size_t,
	pub size_written: *mut size_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_2 {
	pub start: *mut yaml_char_t,
	pub end: *mut yaml_char_t,
	pub pointer: *mut yaml_char_t,
	pub last: *mut yaml_char_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_3 {
	pub start: *mut ::std::os::raw::c_uchar,
	pub end: *mut ::std::os::raw::c_uchar,
	pub pointer: *mut ::std::os::raw::c_uchar,
	pub last: *mut ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_4 {
	pub start: *mut yaml_emitter_state_t,
	pub end: *mut yaml_emitter_state_t,
	pub top: *mut yaml_emitter_state_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_5 {
	pub start: *mut yaml_event_t,
	pub end: *mut yaml_event_t,
	pub head: *mut yaml_event_t,
	pub tail: *mut yaml_event_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_6 {
	pub start: *mut ::std::os::raw::c_int,
	pub end: *mut ::std::os::raw::c_int,
	pub top: *mut ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_7 {
	pub start: *mut yaml_tag_directive_t,
	pub end: *mut yaml_tag_directive_t,
	pub top: *mut yaml_tag_directive_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_8 {
	pub anchor: *mut yaml_char_t,
	pub anchor_length: size_t,
	pub alias: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_9 {
	pub handle: *mut yaml_char_t,
	pub handle_length: size_t,
	pub suffix: *mut yaml_char_t,
	pub suffix_length: size_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yaml_emitter_s__bindgen_ty_10 {
	pub value: *mut yaml_char_t,
	pub length: size_t,
	pub multiline: ::std::os::raw::c_int,
	pub flow_plain_allowed: ::std::os::raw::c_int,
	pub block_plain_allowed: ::std::os::raw::c_int,
	pub single_quoted_allowed: ::std::os::raw::c_int,
	pub block_allowed: ::std::os::raw::c_int,
	pub style: yaml_scalar_style_t,
}
pub type yaml_emitter_t = yaml_emitter_s;
